# Generated by Django 5.2.4 on 2025-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address of the client.', verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time the request was made.', verbose_name='Timestamp')),
                ('path', models.CharField(help_text='The path of the requested URL.', max_length=255, verbose_name='Request Path')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
