# Generated by Django 5.2.4 on 2025-07-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_ip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address to block.', unique=True, verbose_name='Blocked IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the IP was added to the blacklist.', verbose_name='Blocked At')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
