# Generated by Django 5.2.4 on 2025-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_ip', '0002_blockedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='path',
            field=models.CharField(help_text='The path of the requested URL.', max_length=254, verbose_name='Request Path'),
        ),
    ]
