# Generated by Django 5.2.4 on 2025-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_ip', '0003_alter_requestlog_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, help_text='City derived from IP geolocation.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, help_text='Country derived from IP geolocation.', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
