# Generated by Django 5.2.4 on 2025-07-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_ip', '0004_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address flagged as suspicious.', unique=True, verbose_name='Suspicious IP Address')),
                ('reason', models.TextField(help_text='Why this IP was flagged as suspicious.', verbose_name='Reason for Flagging')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, help_text='The time the IP was flagged.', verbose_name='Flagged At')),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-flagged_at'],
            },
        ),
    ]
